task : Operation.hpp project.cpp project.hpp ./parser/Semantic.cpp ./parser/Semantic.hpp ./parser/QueryParser.cpp ./parser/QueryParser.hpp Types.cpp ./parser/CreateParser.cpp ./parser/CreateParser.hpp ./parser/Query.hpp Types.hpp
	g++ -std=c++11 -Wall -O3 -g -o task project.cpp Types.cpp ./parser/Semantic.cpp ./parser/QueryParser.cpp ./parser/CreateParser.cpp -I. -march=native
